// src/data/symptomOptions.ts
export type SymptomOption = {
    value: string;
    label: string;
    weight: number;
};

const symptomOptions: SymptomOption[] = [
    { value: "itching", label: "itching", weight: 1 },
    { value: "skin_rash", label: "skin rash", weight: 3 },
    { value: "nodal_skin_eruptions", label: "nodal skin eruptions", weight: 4 },
    { value: "continuous_sneezing", label: "continuous sneezing", weight: 4 },
    { value: "shivering", label: "shivering", weight: 5 },
    { value: "chills", label: "chills", weight: 3 },
    { value: "joint_pain", label: "joint pain", weight: 3 },
    { value: "stomach_pain", label: "stomach pain", weight: 5 },
    { value: "acidity", label: "acidity", weight: 3 },
    { value: "ulcers_on_tongue", label: "ulcers on tongue", weight: 4 },
    { value: "muscle_wasting", label: "muscle wasting", weight: 3 },
    { value: "vomiting", label: "vomiting", weight: 5 },
    { value: "burning_micturition", label: "burning micturition", weight: 6 },
    { value: "spotting_urination", label: "spotting urination", weight: 6 },
    { value: "fatigue", label: "fatigue", weight: 4 },
    { value: "weight_gain", label: "weight_gain", weight: 3 },
    { value: "anxiety", label: "anxiety", weight: 4 },
    { value: "cold_hands_and_feets", label: "cold hands and feets", weight: 5 },
    { value: "mood_swings", label: "mood swings", weight: 3 },
    { value: "weight_loss", label: "weight loss", weight: 3 },
    { value: "restlessness", label: "restlessness", weight: 5 },
    { value: "lethargy", label: "lethargy", weight: 2 },
    { value: "patches_in_throat", label: "patches in throat", weight: 6 },
    { value: "irregular_sugar_level", label: "irregular sugar level", weight: 5 },
    { value: "cough", label: "cough", weight: 4 },
    { value: "high_fever", label: "high fever", weight: 7 },
    { value: "sunken_eyes", label: "sunken eyes", weight: 3 },
    { value: "breathlessness", label: "breathlessness", weight: 4 },
    { value: "sweating", label: "sweating", weight: 3 },
    { value: "dehydration", label: "dehydration", weight: 4 },
    { value: "indigestion", label: "indigestion", weight: 5 },
    { value: "headache", label: "headache", weight: 3 },
    { value: "yellowish_skin", label: "yellowish skin", weight: 3 },
    { value: "dark_urine", label: "dark urine", weight: 4 },
    { value: "nausea", label: "nausea", weight: 5 },
    { value: "loss_of_appetite", label: "loss of appetite", weight: 4 },
    { value: "pain_behind_the_eyes", label: "pain behind the eyes", weight: 4 },
    { value: "back_pain", label: "back pain", weight: 3 },
    { value: "constipation", label: "constipation", weight: 4 },
    { value: "abdominal_pain", label: "abdominal pain", weight: 4 },
    { value: "diarrhoea", label: "diarrhoea", weight: 6 },
    { value: "mild_fever", label: "mild fever", weight: 5 },
    { value: "yellow_urine", label: "yellow urine", weight: 4 },
    { value: "yellowing_of_eyes", label: "yellowing of eyes", weight: 4 },
    { value: "acute_liver_failure", label: "acute liver failure", weight: 6 },
    { value: "fluid_overload", label: "fluid overload", weight: 6 },
    { value: "swelling_of_stomach", label: "swelling of stomach", weight: 7 },
    { value: "swelled_lymph_nodes", label: "swelled lymph nodes", weight: 6 },
    { value: "malaise", label: "malaise", weight: 6 },
    { value: "blurred_and_distorted_vision", label: "blurred and distorted vision", weight: 5 },
    { value: "phlegm", label: "phlegm", weight: 5 },
    { value: "throat_irritation", label: "throat irritation", weight: 4 },
    { value: "redness_of_eyes", label: "redness of eyes", weight: 5 },
    { value: "sinus_pressure", label: "sinus pressure", weight: 4 },
    { value: "runny_nose", label: "runny nose", weight: 5 },
    { value: "congestion", label: "congestion", weight: 5 },
    { value: "chest_pain", label: "chest pain", weight: 7 },
    { value: "weakness_in_limbs", label: "weakness in limbs", weight: 7 },
    { value: "fast_heart_rate", label: "fast heart rate", weight: 5 },
    { value: "pain_during_bowel_movements", label: "pain during bowel movements", weight: 5 },
    { value: "pain_in_anal_region", label: "pain in anal region", weight: 6 },
    { value: "bloody_stool", label: "bloody stool", weight: 5 },
    { value: "irritation_in_anus", label: "irritation in anus", weight: 6 },
    { value: "neck_pain", label: "neck pain", weight: 5 },
    { value: "dizziness", label: "dizziness", weight: 4 },
    { value: "cramps", label: "cramps", weight: 4 },
    { value: "bruising", label: "bruising", weight: 4 },
    { value: "obesity", label: "obesity", weight: 4 },
    { value: "swollen_legs", label: "swollen legs", weight: 5 },
    { value: "swollen_blood_vessels", label: "swollen blood vessels", weight: 5 },
    { value: "puffy_face_and_eyes", label: "puffy face and eyes", weight: 5 },
    { value: "enlarged_thyroid", label: "enlarged thyroid", weight: 6 },
    { value: "brittle_nails", label: "brittle nails", weight: 5 },
    { value: "swollen_extremeties", label: "swollen extremeties", weight: 5 },
    { value: "excessive_hunger", label: "excessive hunger", weight: 4 },
    { value: "extra_marital_contacts", label: "extram arital contacts", weight: 5 },
    { value: "drying_and_tingling_lips", label: "drying and tingling_lips", weight: 4 },
    { value: "slurred_speech", label: "slurred speech", weight: 4 },
    { value: "knee_pain", label: "knee pain", weight: 3 },
    { value: "hip_joint_pain", label: "hip joint pain", weight: 2 },
    { value: "muscle_weakness", label: "muscle weakness", weight: 2 },
    { value: "stiff_neck", label: "stiff neck", weight: 4 },
    { value: "swelling_joints", label: "swelling joints", weight: 5 },
    { value: "movement_stiffness", label: "movement stiffness", weight: 5 },
    { value: "spinning_movements", label: "spinning movements", weight: 6 },
    { value: "loss_of_balance", label: "loss of balance", weight: 4 },
    { value: "unsteadiness", label: "unsteadiness", weight: 4 },
    { value: "weakness_of_one_body_side", label: "weakness of one body side", weight: 4 },
    { value: "loss_of_smell", label: "loss of smell", weight: 3 },
    { value: "bladder_discomfort", label: "bladder discomfort", weight: 4 },
    { value: "foul_smell_ofurine", label: "foul smell of urine", weight: 6 },
    { value: "continuous_feel_of_urine", label: "continuous feel of urine", weight: 4 },
    { value: "passage_of_gases", label: "passage of gases", weight: 4 },
    { value: "internal_itching", label: "internal itching", weight: 3 },
    { value: "toxic_look_(typhos)", label: "toxic look (typhos)", weight: 6 },
    { value: "depression", label: "depression", weight: 4 },
    { value: "irritability", label: "irritability", weight: 4 },
    { value: "muscle_pain", label: "muscle pain", weight: 3 },
    { value: "altered_sensorium", label: "altered sensorium", weight: 5 },
    { value: "red_spots_over_body", label: "red spots over body", weight: 5 },
    { value: "belly_pain", label: "belly pain", weight: 5 },
    { value: "abnormal_menstruation", label: "abnormal menstruation", weight: 5 },
    { value: "dischromic_patches", label: "dischromic patches", weight: 4 },
    { value: "watering_from_eyes", label: "watering from eyes", weight: 3 },
    { value: "increased_appetite", label: "increased appetite", weight: 4 },
    { value: "polyuria", label: "polyuria", weight: 6 },
    { value: "family_history", label: "family history", weight: 3 },
    { value: "mucoid_sputum", label: "mucoid sputum", weight: 5 },
    { value: "rusty_sputum", label: "rusty sputum", weight: 5 },
    { value: "lack_of_concentration", label: "lack of concentration", weight: 4 },
    { value: "visual_disturbances", label: "visual disturbances", weight: 4 },
    { value: "receiving_blood_transfusion", label: "receiving blood transfusion", weight: 6 },
    { value: "receiving_unsterile_injections", label: "receiving unsterile injections", weight: 6 },
    { value: "coma", label: "coma", weight: 7 },
    { value: "stomach_bleeding", label: "stomach bleeding", weight: 6 },
    { value: "distention_of_abdomen", label: "distention of abdomen", weight: 6 },
    { value: "history_of_alcohol_consumption", label: "history of alcohol consumption", weight: 5 },
    { value: "fluid_overload", label: "fluid overload", weight: 5 },
    { value: "blood_in_sputum", label: "blood in sputum", weight: 6 },
    { value: "prominent_veins_on_calf", label: "prominent veins on calf", weight: 4 },
    { value: "palpitations", label: "palpitations", weight: 4 },
    { value: "painful_walking", label: "painful walking", weight: 3 },
    { value: "pus_filled_pimples", label: "pus filled pimples", weight: 4 },
    { value: "blackheads", label: "blackheads", weight: 3 },
    { value: "scurring", label: "scurring", weight: 3 },
    { value: "skin_peeling", label: "skin peeling", weight: 3 },
    { value: "silver_like_dusting", label: "silver like dusting", weight: 4 },
    { value: "small_dents_in_nails", label: "small dents in nails", weight: 4 },
    { value: "inflammatory_nails", label: "inflammatory nails", weight: 4 },
    { value: "blister", label: "blister", weight: 5 },
    { value: "red_sore_around_nose", label: "red sore around nose", weight: 4 },
    { value: "yellow_crust_ooze", label: "yellow crust ooze", weight: 5 },

];

export default symptomOptions;
